"""000 - init

Revision ID: 4a727cb4c953
Revises:
Create Date: 2023-06-21 00:26:09.550094

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '4a727cb4c953'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # enables UUID extention in PSQL
    conn = op.get_bind()
    conn.execute(sa.text('CREATE EXTENSION IF NOT EXISTS "uuid-ossp";'))

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'role',
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('id', sa.Uuid(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table(
        'user',
        sa.Column('email', sa.String(), nullable=False),
        sa.Column('password_hash', sa.String(), nullable=False),
        sa.Column('is_active', sa.Boolean(), nullable=False),
        sa.Column('confirmed_at', sa.DateTime(), nullable=True),
        sa.Column('last_login_at', sa.DateTime(), nullable=True),
        sa.Column('last_login_ip', sa.String(), nullable=True),
        sa.Column('reset_code_hash', sa.String(), nullable=True),
        sa.Column('reset_code_expiration', sa.DateTime(), nullable=True),
        sa.Column('id', sa.Uuid(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_table(
        'roles_users',
        sa.Column('user_id', sa.Uuid(), nullable=False),
        sa.Column('role_id', sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(['role_id'], ['role.id']),
        sa.ForeignKeyConstraint(['user_id'], ['user.id']),
        sa.PrimaryKeyConstraint('user_id', 'role_id'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('roles_users')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_table('role')
    # ### end Alembic commands ###
